### ISSUE TITLE
@spectrum-icons/workflow dependency is missing

### ISSUE THREAD

**Issue by icaraps** [adobe/generator-aio-app#113]
If you chose the react app with `aio app init`, when you try to build the app you will face the issue: `Error: Cannot find module '@spectrum-icons/workflow'`

This seems to be because an icon from that package is imported here https://github.com/adobe/generator-aio-app/blob/0e7e61bb623dec763ddf5ce89cacf12667ae4c99/generators/add-web-assets/exc-react/templates/src/components/ActionsForm.js#L31

but the dependency `@spectrum-icons/workflow` is never defined see https://github.com/adobe/generator-aio-app/blob/508b42c7d04ed50efa39513a6b4452099d9c513d/generators/add-web-assets/exc-react/index.js#L55-L64

See https://react-spectrum.adobe.com/react-spectrum/workflow-icons.html for more info about spectrum workflow icons.

**Comment by icaraps** [comment]
Here's the PR https://github.com/adobe/generator-aio-app/pull/114

**Comment by meryllblanchet** [comment]
Thanks for this contribution @icaraps !
@rajarju @purplecabbage could you have a look at PR #114 ?
