### ISSUE TITLE
documentation wrong: aio app deploy -s parameter does not exist

### ISSUE THREAD

**Issue by tripodsan** [adobe/generator-aio-app#16]
### Expected Behaviour
the https://github.com/adobe/generator-aio-app/tree/master/generators/app/templates#deploy--cleanup has outdated description.

it should be matched to the actual commands
https://github.com/adobe/aio-cli#aio-appdeploy
```
 --skip-actions       Skip action build & deploy
  --skip-build         Skip build phase
  --skip-deploy        Skip deploy phase
  --skip-static        Skip build & deployment of static files
```

proposed changes:

> Each of the above commands can either be run for actions or static files, append  `--skip-static` or `--skip-actions`, for example aio app deploy `--skip-actions` will only build and deploy static files.

**Comment by moritzraho** [comment]
@tripodsan thanks for reporting
