### ISSUE TITLE
.gitignore is not created 

### ISSUE THREAD

**Issue by icaraps** [adobe/generator-aio-app#19]
### Expected Behaviour
.gitignore is created

### Actual Behaviour
.gitignore is not created

#### Steps to Reproduce
`npm i -g @adobe/aio-cli && aio app init`

#### Platform and Version
`@adobe/aio-cli@3.0.0`

**Comment by meryllblanchet** [comment]
cc @moritzraho

**Comment by moritzraho** [comment]
@meryllblanchet  @icaraps ok I found the issue, npm is not including the .gitignore template file!

**Comment by moritzraho** [comment]
fixed in #20
