### ISSUE TITLE
Broken README link

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/generator-aio-app#198]
### Expected Behaviour

The link to [experience cloud shell react generator](https://github.com/adobe/generator-aio-app/blob/master/generators/add-web-assets/exc-react/index.js) points to the relevant source file.

### Actual Behaviour

Clicking on the link leads to a 404. Where did that code go?

**Comment by shazron** [comment]
It is here now, it is a template https://github.com/adobe/generator-app-excshell that will be installed by `aio app init` by querying the Template Registry API. Upcoming feature.

**Comment by meryllblanchet** [comment]
Thanks for the pointer, Shaz!

**Comment by shazron** [comment]
Fixed the link

**Comment by meryllblanchet** [comment]
Works! Closing the issue, thanks for the quick fix ;-)
