### ISSUE TITLE
Util.js could have a non-web actionInvoke function

### ISSUE THREAD

**Issue by PulkitChadhaAdobe** [adobe/generator-aio-app#29]
Util.js could have a non-web actionInvoke function

I think it will be great if we have a function to invoke internal actions as the ones I have for authentication and backend processing. I started to write one but don’t quite know how to get the global parameters from

**Comment by moritzraho** [comment]
@PulkitChadhaAdobe thanks for your input!

I don't think there are many use cases where it would make sense to invoke a non web function from the UI as you would need the AIO_RUNTIME_AUTH key to be accessible from the UI.
But maybe I am wrong :)
Could you tell us a little more on why do you need a non web action ?

**Comment by moritzraho** [comment]
@PulkitChadhaAdobe closing that one as for now the UI should only invoke web actions, let me know if you feel it should be reopened
