### ISSUE TITLE
How do I add a generator?

### ISSUE THREAD

**Issue by purplecabbage** [adobe/generator-aio-app#3]
The directory structure is not obvious, so we need some documentation in the README about how to add a new generator so that it will be picked up by aio-cli-plugin-app init without any need to re-pub aio-cli-plugin-app.

**Comment by moritzraho** [comment]
Thanks for the comment 

@purplecabbage see the PR in aio-cli-plugin-app: https://github.com/adobe/aio-cli-plugin-app/pull/113

There is no need to republish the aio-cli-plugin-app, the only generator that init needs to know about is `app` which is loaded by default by yeoman when doing register/require (see https://github.com/adobe/aio-cli-plugin-app/pull/113/files#diff-f3f6f06974db8060723f7350db40817dR36)

The app generator (https://github.com/adobe/generator-aio-app/blob/master/generators/app/index.js) then calls the add-action and add-web-assets generators internally. Those two generators call actual code generators for actions and web-assets. This means that actual code generators for ui and actions do not need to be known by aio-cli-plugin-app, but instead generator-aio-app will prompt the user for which action/ui to generate.

New action/ui generator can be added to generator-aio-app in the `generators/add-action/xyz/` or `generators/add-web-assets/xyz/` folder.
I will add some doc to it.

**Comment by moritzraho** [comment]
Also in this PR I am adding your exc-shell generator as a new UI generator 
https://github.com/adobe/generator-aio-app/pull/4

**Comment by moritzraho** [comment]
fixed in #5
