### ISSUE TITLE
Numerous uses of webAssetsDirname

### ISSUE THREAD

**Issue by purplecabbage** [adobe/generator-aio-app#34]
`const { webAssetsDirname } = require('../../lib/constants')`
We have several spots where generator code is reading `webAssetsDirname` from its own constants, however this is a dynamic folder-name that can differ from project to project.  The correct approach is to read `cna.web` from the .aio file in the project root.

**Comment by moritzraho** [comment]
👍 this should be fixed in aio-cli-plugin-app checks too, e.g. https://github.com/adobe/aio-cli-plugin-app/blob/master/src/commands/app/deploy.js#L73

**Comment by meryllblanchet** [comment]
@moritzraho @purplecabbage do you confirm that it is fixed?
