### ISSUE TITLE
React-Spectrum SPA generator enhancements

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/generator-aio-app#58]
@icaraps has several proposals to improve the generator:

- Prevent usage of UNSAFE_className
- Routing samples

He's going to add more details and contribute to the proposed changes.

**Comment by icaraps** [comment]
I propose to enhance the current template with: 
* Use the Grid layout as shown in the example https://reactspectrum.blob.core.windows.net/reactspectrum/3b9f6d3876c63cd08a3563867dcb1f63675ac8b9/docs/react-spectrum/layout.html#defining-grids to better structure the global layout of the App with a header, sidenav, main content and optionally footer
* Leverage react-router HashRouter to showcase routing https://reacttraining.com/react-router/web/api/HashRouter which plays well inside the Unified Shell. DDAM is using it as well.
* Add `tsconfig.json` file under the `web-src` folder to support TypeScript by default as React Spectrum is written in TypeScript. Config is only necessary to support JSX (see https://en.parceljs.org/typeScript.html#when-using-react for details): 
```
{
  "compilerOptions": {
    "jsx": "react"
  }
} 
``` 

Feedback is welcomed !

**Comment by duynguyen** [comment]
+1 for using react spectrum recommended styling and grid layout.
I doubt everybody will need HashRouter (which then becomes a hassle to remove for anyone not needing it). I would rather create sample apps for router instead of embedding it directly in the template.

**Comment by icaraps** [comment]
As for the React app itself, IMO it should be based on https://github.com/facebook/create-react-app to enforce best practices.

**Comment by icaraps** [comment]
Also I wonder why there's a 404.html file ? I thought the ExC Shell is already handling 404s ?

**Comment by meryllblanchet** [comment]
@rajarju @purplecabbage could you have a look?
