### ISSUE TITLE
Support multiple test frameworks

### ISSUE THREAD

**Issue by purplecabbage** [adobe/generator-aio-app#65]
Currently everything is very opinionated towards the use of jest
Some templates / actions might come with their own opinions, so we should allow multiple test methods and have it overridable in package.json scripts/test.

Phase 1:
- allow the use of  --passWithNoTests by default, in case action templates no not add any jest tests
Phase 2:
- something more robust

**Comment by meryllblanchet** [comment]
@purplecabbage would the first option be sufficient until we have a clear requirement that would need to "something more robust"?

cc @sarahxxu

**Comment by purplecabbage** [comment]
first option is implemented
