### ISSUE TITLE
Initial generated app is broken

### ISSUE THREAD

**Issue by kptdobe** [adobe/generator-aio-app#91]
I just used `aio app init helix-purge`, went through all steps, run locally, open browser and I get a weird error message.

### Expected Behaviour
I expect a basic default app showing me "something working".

If more steps are required, I would expect to be informed.

### Actual Behaviour
I get error message "Something went wrong :("

#### Steps to Reproduce

Run `aio app init helix-purge`.
Select an org, a project (previously created with Firefly template), "production" workspace.
Then I unselected only the Events.
From there, just run `aio app run --local`

#### Platform and Version
@adobe/aio-cli@3.7.0
Node v10.21.0

<img width="1031" alt="Screenshot 2020-08-14 at 09 44 58" src="https://user-images.githubusercontent.com/474200/90226129-d3a7f980-de12-11ea-995b-26d82098d8b4.png">

**Comment by meryllblanchet** [comment]
Thanks for reporting the issue, @kptdobe !
Could I ask you to use `aio info` and add the output into a comment? This will be helpful for us to support further.

**Comment by kptdobe** [comment]
```
$ aio info

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.80 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 3.7.0
  CLI plugins:
    @adobe/aio-cli 3.7.0 (core)
    @adobe/aio-cli-plugin-app 3.2.0 (user)
    @oclif/plugin-help 2.2.3 (core)
    @oclif/plugin-not-found 1.2.4 (core)
    @oclif/plugin-plugins 1.9.0 (core)
    @oclif/plugin-autocomplete 0.2.0 (core)
    @adobe/aio-cli-plugin-config 2.3.0 (core)
    @oclif/plugin-warn-if-update-available 1.7.0 (core)
    @adobe/aio-cli-plugin-auth 2.4.0 (core)
    @adobe/aio-cli-plugin-console 3.2.0 (core)
    @adobe/aio-cli-plugin-certificate 0.2.0 (core)
    @adobe/aio-cli-plugin-info 1.1.0 (core)
    @adobe/aio-cli-plugin-events 1.1.0 (core)
    @adobe/aio-cli-plugin-runtime 1.10.0 (core)
```

**Comment by meryllblanchet** [comment]
Solved together with @kptdobe: the user installed `@adobe/aio-cli-plugin-app 3.2.0` plugin has been uninstalled, reverting to the latest `@adobe/aio-cli-plugin-app 3.5.1 (core)` embedded within `@adobe/aio-cli: 3.7.0`.

**Comment by kptdobe** [comment]
Thanks @meryllblanchet for the support!

Note that before uninstalling the user plugin, I ran:

```
aio update
warning: the user-installed plugin(s) below have versions older or equal to the core plugin versions, and should be uninstalled via aio plugins:uninstall <plugin_name>
Plugin(s) to uninstall    Current   Latest 
@adobe/aio-cli-plugin-app 3.5.1     3.5.1  
```

I think the current version displayed here should have been `3.2.0` here (see info above) and not `3.5.1`. Might be a bug.

**Comment by meryllblanchet** [comment]
@shazron, could this be a bug in the `aio update` listing?

**Comment by shazron** [comment]
I did a code inspection. The `current` version is read from disk https://github.com/adobe/aio-cli/blob/d9882ade89625c24f68999fb7cbe70d04e189fa7/src/commands/update.js#L141. It's possible that it could have gone out of sync (updated async somehow)
